### ISSUE TITLE
Migrating to Spring Boot 2 (2.0.0.M5)

### ISSUE THREAD

**Issue by bboyz269** [kakawait/uaa-behind-zuul-sample#29]
Hi,  

I'm trying to build a system with services discovery Eureka, UAA server (spring oauth2) and a Zuul as gateway. I tried to use this project as a starting points. But I'm having hard time with migrating to Spring Boot 2 as there's lots of things moved or removed. Things I'm missing so far:
* Annotation `EnableOauth2Sso`
* Intefarce `UserInfoRestTemplateCustomizer`
* Bean of type `ResourceServerTokenServices`

// They all belongs to spring-boot-autoconfigure:1.5.7.RELEASE packages.
  
So I would like to ask if there's any chance you can migrate this project to Spring Boot 2.0 soon. It's also great if you can help me with those above.

Thanks in advance.

**Comment by kakawait** [comment]
Hi @bboyz269 

Yes project was not designed and tested on Spring boot 2 that should explain why it can't work.

Any chance to work: yes but really soon: no. For two reasons:

1. I want to wait Spring Security 5 ans Spring boot 2 to be released as GA
2. I would work on new gateway Spring Gateway in ordre to drop Zuul Gateway

Today i can't help you since i'm not starting playing with Spring boot 2. I have to test it a bit before

**Comment by bboyz269** [comment]
I'll try this Spring Cloud Gateway as alternative. Thanks for the info!
